export enum ActionType {
  ACCEPT_SELL_OFFER = 'ACCEPT_SELL_OFFER',
  CHANGE_FOCUS = 'CHANGE_FOCUS',
  DECLARE_WAR = 'DECLARE_WAR',
  REQUEST_ALLY = 'REQUEST_ALLY',
  ACCEPT_ALLY_REQUEST = 'ACCEPT_ALLY_REQUEST',
  REFUSE_ALLY_REQUEST = 'REFUSE_ALLY_REQUEST',
  REQUEST_PEACE = 'REQUEST_PEACE',
  ACCEPT_PEACE_REQUEST = 'ACCEPT_PEACE_REQUEST',
  REFUSE_PEACE_REQUEST = 'REFUSE_PEACE_REQUEST',
  SHOP = 'SHOP',
  IMPROVE_RELATIONS = 'IMPROVE_RELATIONS',
  SEND_INSULT = 'SEND_INSULT',
  SEND_RESOURCES = 'SEND_RESOURCES',
  CREATE_COALITION = 'CREATE_COALITION',
  JOIN_COALITION = 'JOIN_COALITION',
  IMPROVE_PROVINCES = 'IMPROVE_PROVINCES',
  NEXT_TURN = 'NEXT_TURN',
  JOIN_WAR = 'JOIN_WAR',
  REFUSE_JOIN_WAR = 'REFUSE_JOIN_WAR',
  DISMISS_ARMY = 'DISMISS_ARMY',
  GUARANTEE_INDEPENDENCE = 'GUARANTEE_INDEPENDENCE',
  REMOVE_INDEPENDENCE_GUARANTEEING = 'REMOVE_INDEPENDENCE_GUARANTEEING',
  DEMAND = 'DEMAND',
  BREAK_ALLIANCE = 'BREAK_ALLIANCE',
}

export type Action = {
  type: ActionType;
  playerId?: string;
  gameId?: string;
  countryId?: string;
  targetId?: string;
  data: ActionData;
};

export type ActionData = any;
